### ISSUE TITLE
InvalidStateError in ProofView

### ISSUE THREAD

**Issue by benedictleejh** [siegebell/vscoq#116]
When opening a Coq source file, the ProofView opens, then flashes the error:

```
!InvalidStateError: Failed to execute 'send' on 'WebSocket':
Still in CONNECTING state.
```

before simply showing "Not running". Repeatedly pressing refresh shows the same error. I've tried changing both `coqtop.binPath` and `coq.externalViewUrlCommand` to no avail.

Closing the file and reopening it throws an error in the developer console:

```
Cannot read property 'viewColumn' of undefined: TypeError: Cannot read property 'viewColumn' of undefined
    at CoqDocument.currentViewColumn (/home/xerafion/.vscode/extensions/siegebell.vscoq-0.2.7/out/src/CoqDocument.js:173:50)
    at new CoqDocument (~/.vscode/extensions/siegebell.vscoq-0.2.7/out/src/CoqDocument.js:57:58)
    at CoqProject.tryLoadDocument (~/.vscode/extensions/siegebell.vscoq-0.2.7/out/src/CoqProject.js:79:37)
    at CoqProject.onDidOpenTextDocument (~/.vscode/extensions/siegebell.vscoq-0.2.7/out/src/CoqProject.js:96:14)
    at CoqProject.vscode.workspace.onDidOpenTextDocument (~/.vscode/extensions/siegebell.vscoq-0.2.7/out/src/CoqProject.js:32:65)
    at e.invoke (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:31992)
    at e.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:8945)
    at t.$acceptModelAdd (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:10:31769)
    at t.e.handle (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:10:4203)
    at s (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:7:11178)
```

This may or may not be related, as the first error would still pop up when opening VSCode and a Coq source file is open.

This happens on both OS X 10.10.5, and Linux.

VSCode version: 1.8.1
VSCoq version: 0.2.7

Coq settings on Linux:

```
"coqtop.binPath": "/usr/bin",
"coq.externalViewUrlCommand": "firefox ${url}"
```

**Comment by siegebell** [comment]
Does the error prevent interpreting the source or break any other features?

**Comment by benedictleejh** [comment]
Interpreting the source still seems to be fine, which suggests this is a minor error.

**Comment by siegebell** [comment]
@benedictleejh I cannot actually reproduce this issue, but I did just fix a bug that might be causing it. I'll probably publish an update in a week or less with the change.

**Comment by artagnon** [comment]
I have this issue on macOS. <kbd>Ctrl</kbd>+<kbd>Cmd</kbd>+<kbd>Down</kbd> doesn't seem to do anything for the ProofView window either: Not sure what display I'm supposed to get on the ProofView window. I've set `binPath` correctly, and verified that `coqtop` works.

**Comment by alexozer** [comment]
I too still have this error, but on Arch Linux.

**Comment by artagnon** [comment]
Seems to be fine now actually, after restarting vscode. Thanks for the plugin!

**Comment by alexozer** [comment]
Yeah eventually got it to work.

**Comment by vinothkr** [comment]
Same error for me, I tried with even the latest vscode. I seem to be getting only "Not running" on the proof view. Can anyone let me know how you got it working? I am on "Elementary OS"

**Comment by alexozer** [comment]
@vinothkr I just had to begin stepping through the proof. I think this is just a normal Coq state.

**Comment by takanuva** [comment]
Same issue here (macOS). Stepping through the proof works, but the error message flashes quickly at each time.

**Comment by gldubc** [comment]
Same issue here on Archlinux.
